# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-win-lib:
    # The type of runner that the job will run on
    runs-on: windows-2022
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: Get-PSDrive
      - name: Cache depot_tools
        id: cache-depot-tools
        uses: actions/cache@v3
        with:
          path: C:\depot_tools
          key: ${{ runner.os }}-depot-tools
  
      - name: Download depot_tools
        if: steps.cache-depot-tools.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile "C:\depot_tools.zip"
          Expand-Archive -LiteralPath 'C:\depot_tools.zip' -DestinationPath 'C:\depot_tools'

      - name: Add depot_tools to path
        run: Add-Content $env:GITHUB_PATH "C:\depot_tools"

      - run: gclient
        shell: cmd
      - name: Configure Git
        shell: cmd
        run: git config --global core.autocrlf false && git config --global core.filemode false
      - name: Download V8
        shell: cmd
        run: |
          C:
          mkdir v8
          cd v8
          fetch v8
      - name: Download build dependencies
        working-directory: C:/v8/v8
        shell: cmd
        run: gclient sync
      - name: Generate Build Files
        working-directory: C:/v8/v8
        shell: cmd
        run: python3 tools\dev\v8gen.py x64.release
      - name: Configure Build
        working-directory: C:/v8/v8
        shell: bash
        run: |
          # echo "is_component_build = false" >> out.gn/x64.release/args.gn
          # echo "v8_static_library = true" >> out.gn/x64.release/args.gn
          echo "treat_warnings_as_errors = false" >> out.gn/x64.release/args.gn
          echo "use_custom_libcxx = false" >> out.gn/x64.release/args.gn
          echo "v8_use_external_startup_data = false" >> out.gn/x64.release/args.gn
          echo "v8_monolithic = true" >> out.gn/x64.release/args.gn
          cat out.gn/x64.release/args.gn
      - name: Run Build
        working-directory: C:/v8/v8
        shell: cmd
        run: ninja -C out.gn\x64.release v8_monolith
      - uses: actions/upload-artifact@v3
        with:
          name: v8_win_x64_release_monolith
          path: C:/v8/v8/out.gn/x64.release
